spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource: #database
    primary:  # 本地数据库
      name: WS #数据库名称，oracle必须使用大写
      jdbc-url: jdbc:mysql://39.106.183.62:3306/rrltest?useUnicode=true&amp;characterEncoding=UTF8
      username: test
      password: RRLtest@1012
      type: mysql #数据库类型，
    secondary:  # 本地数据库
      name: WS
      jdbc-url: jdbc:mysql://39.106.183.62:3306/rrltest?useUnicode=true&amp;characterEncoding=UTF8
      username: test
      password: RRLtest@1012
      type: mysql